# Generated by Django 4.2 on 2023-05-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("country", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("has_passed", models.BooleanField()),
                ("track", models.URLField()),
                ("comments", models.TextField()),
            ],
            options={
                "ordering": ["date"],
            },
        ),
    ]
