# Generated by Django 4.2 on 2023-05-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race",
            name="has_passed",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
