# Generated by Django 4.2 on 2023-05-04 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("races", "0002_alter_race_has_passed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="race",
            name="has_passed",
        ),
    ]
